<Workspace Version="0.7.0.23736" X="271.629403728433" Y="100.105239371258" zoom="0.951530808445309" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="c2e14e8c-c8e7-48a3-a8f6-04ba1b001c38" nickname="Select Model Element" x="-209.110901454745" y="-24.7104357395291" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="582c603b-14c1-4994-a0c0-bcf6663d7334-0000778e" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="24ff054a-faa0-4d87-ab75-6a567d417b4d" nickname="Select Model Element" x="-209.110901454745" y="247.747004507081" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="582c603b-14c1-4994-a0c0-bcf6663d7334-000077da" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="6c36dda2-bf37-456f-aa23-85df34ccf1be" nickname="Curve.PointAtParameter" x="472.729895307079" y="52.460158865421" isVisible="true" isUpstreamVisible="true" lacing="Longest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="52cee05b-8747-4d08-9701-8e0b457d4ef1" nickname="CurveElement.Curve" x="187.475127416697" y="-24.7104357395291" isVisible="true" isUpstreamVisible="true" lacing="Disabled" assembly="..\..\Revit_2014\RevitNodes.dll" function="Revit.Elements.CurveElement.Curve" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="50017b6f-f0a9-4640-90c2-8786beda8f9d" nickname="Code Block" x="187.475127416697" y="71.460158865421" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0..1..#x;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="41100889-c587-4daa-ab4d-8a4f885e6f6f" nickname="Curve.PointAtParameter" x="472.729895307079" y="247.747004507081" isVisible="true" isUpstreamVisible="true" lacing="Longest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="bf2a7f83-abba-4f7d-9409-c9f10aed0404" nickname="CurveElement.Curve" x="187.475127416697" y="247.747004507081" isVisible="true" isUpstreamVisible="true" lacing="Disabled" assembly="..\..\Revit_2014\RevitNodes.dll" function="Revit.Elements.CurveElement.Curve" />
    <Dynamo.Nodes.Watch type="Dynamo.Nodes.Watch" guid="9d33c1dc-3a59-497c-a75c-3e45f9190c19" nickname="Watch" x="1002.25498240719" y="148.646647752841" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="ffd5f9a2-95b1-4bd0-915d-36bdfed323c5" nickname="Python Script" x="756.231765656282" y="148.646647752841" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="2">
      <Script>import clr
clr.AddReference("RevitNodes")
clr.AddReference('ProtoGeometry')
from Revit.Elements import *
from Autodesk.DesignScript.Geometry import *

leftPts = IN[0]
rightPts = IN[1]

lines = []
for left, right in zip(leftPts, rightPts):
	line = Line.ByStartPointEndPoint(left, right)
	crv = ModelCurve.ByCurve(line)
	lines.append(crv)

OUT = lines</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.IntegerSlider type="Dynamo.Nodes.IntegerSlider" guid="06da3201-ed26-4e6c-8da2-7104dec4a25d" nickname="Integer Slider" x="-215.110901454745" y="71.460158865421" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Int32>4</System.Int32>
      <Range min="0" max="20" />
    </Dynamo.Nodes.IntegerSlider>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="c2e14e8c-c8e7-48a3-a8f6-04ba1b001c38" start_index="0" end="52cee05b-8747-4d08-9701-8e0b457d4ef1" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="24ff054a-faa0-4d87-ab75-6a567d417b4d" start_index="0" end="bf2a7f83-abba-4f7d-9409-c9f10aed0404" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6c36dda2-bf37-456f-aa23-85df34ccf1be" start_index="0" end="ffd5f9a2-95b1-4bd0-915d-36bdfed323c5" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="52cee05b-8747-4d08-9701-8e0b457d4ef1" start_index="0" end="6c36dda2-bf37-456f-aa23-85df34ccf1be" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="50017b6f-f0a9-4640-90c2-8786beda8f9d" start_index="0" end="6c36dda2-bf37-456f-aa23-85df34ccf1be" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="50017b6f-f0a9-4640-90c2-8786beda8f9d" start_index="0" end="41100889-c587-4daa-ab4d-8a4f885e6f6f" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="41100889-c587-4daa-ab4d-8a4f885e6f6f" start_index="0" end="ffd5f9a2-95b1-4bd0-915d-36bdfed323c5" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="bf2a7f83-abba-4f7d-9409-c9f10aed0404" start_index="0" end="41100889-c587-4daa-ab4d-8a4f885e6f6f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ffd5f9a2-95b1-4bd0-915d-36bdfed323c5" start_index="0" end="9d33c1dc-3a59-497c-a75c-3e45f9190c19" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="06da3201-ed26-4e6c-8da2-7104dec4a25d" start_index="0" end="50017b6f-f0a9-4640-90c2-8786beda8f9d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>