<Workspace Version="0.7.0.23736" X="227.805327380953" Y="-37.542619047619" zoom="1.1575" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="63c661d4-6083-46ac-ab46-d8e5176fb5d4" nickname="Select Model Element" x="-18.4000000000001" y="169.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="582c603b-14c1-4994-a0c0-bcf6663d7334-0000778e" />
    </Dynamo.Nodes.DSModelElementSelection>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="a12cf7c9-ebde-4106-94d5-12ec21919e6f" nickname="Python Script" x="201.501162790698" y="169.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>#derived from Nathan Miller's example http://theprovingground.wikidot.com/revit-api-py-curves

# Default imports
import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
clr.AddReference('RevitServices')
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
import Autodesk
from Autodesk.Revit.DB import *
from RevitServices import *
import math

doc = Persistence.DocumentManager.Instance.CurrentDBDocument

crv = IN[0]
crvRef = crv.InternalElement.GeometryCurve
refptarr = ReferencePointArray()

Transactions.TransactionManager.Instance.EnsureInTransaction(doc)

#use for loop to create a series of points
steps = 20
for i in range(0,steps+1):
    pt = crvRef.Evaluate(float(i)/steps,1) # returns and XYZ
    x = pt.X
    y = pt.Y
    z = pt.Z + math.sin(i)*steps 
    myXYZ = XYZ(x,y,z)
    refPt = doc.FamilyCreate.NewReferencePoint(myXYZ)
    refptarr.Append(refPt)
crv2 = doc.FamilyCreate.NewCurveByPoints(refptarr)

Transactions.TransactionManager.Instance.TransactionTaskDone()

OUT = crv2.ToDSType(False)
</Script>
    </DSIronPythonNode.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="63c661d4-6083-46ac-ab46-d8e5176fb5d4" start_index="0" end="a12cf7c9-ebde-4106-94d5-12ec21919e6f" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>