<Workspace Version="0.7.0.23736" X="34.630952380953" Y="88.952380952381" zoom="1" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="8632dddf-d923-4cfa-b128-2fed136507d3" nickname="Select Model Element" x="85.0000000000001" y="10.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="582c603b-14c1-4994-a0c0-bcf6663d7334-000079c0" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="5a6e0f00-c9be-41a9-8d6f-931b304d5f3b" nickname="Select Model Element" x="85.0000000000001" y="118.75" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="582c603b-14c1-4994-a0c0-bcf6663d7334-000079e5" />
    </Dynamo.Nodes.DSModelElementSelection>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="c925d90d-be67-4567-a496-74f203e8ed2a" nickname="Python Script" x="319.501162790698" y="42" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="2">
      <Script>#derived from Nathan Miller's example http://theprovingground.wikidot.com/revit-api-py-curves

# Default imports
import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
clr.AddReference('RevitServices')
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
import Autodesk
from Autodesk.Revit.DB import *
from RevitServices import *
import math

doc = Persistence.DocumentManager.Instance.CurrentDBDocument

# get the input points
beginPoint = IN[0].InternalElement
endPoint = IN[1].InternalElement

lineRefPointArray = ReferencePointArray()
lineRefPointArray.Append(beginPoint)
lineRefPointArray.Append(endPoint)

Transactions.TransactionManager.Instance.EnsureInTransaction(doc)

crv = doc.FamilyCreate.NewCurveByPoints(lineRefPointArray)
crvRef = crv.GeometryCurve
refptarr = ReferencePointArray()

#use for loop to create a series of points
steps = 20
for i in range(0,steps+1):
    pt = crvRef.Evaluate(float(i)/steps,1) # returns and XYZ
    x = pt.X
    y = pt.Y
    z = pt.Z + math.sin(i)*steps 
    myXYZ = XYZ(x,y,z)
    refPt = doc.FamilyCreate.NewReferencePoint(myXYZ)
    refptarr.Append(refPt)
crv2 = doc.FamilyCreate.NewCurveByPoints(refptarr)

Transactions.TransactionManager.Instance.TransactionTaskDone()

OUT = crv2.ToDSType(False)</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Watch type="Dynamo.Nodes.Watch" guid="09733fa5-d8c0-4005-81c3-6b092175cc6f" nickname="Watch" x="517.369047619047" y="42.047619047619" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="8632dddf-d923-4cfa-b128-2fed136507d3" start_index="0" end="c925d90d-be67-4567-a496-74f203e8ed2a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5a6e0f00-c9be-41a9-8d6f-931b304d5f3b" start_index="0" end="c925d90d-be67-4567-a496-74f203e8ed2a" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="c925d90d-be67-4567-a496-74f203e8ed2a" start_index="0" end="09733fa5-d8c0-4005-81c3-6b092175cc6f" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Select two points." x="98" y="206" />
    <Dynamo.Models.NoteModel text="Make a python script." x="317" y="158" />
  </Notes>
</Workspace>